pipeline {
    agent any
    
    environment {
		DOCKERHUB_CREDENTIALS=credentials('credential-docker')
		YOUR_DOCKERHUB_USERNAME="ulviibadov"
        SERVICE_NAME = "frontend-app-service"
        REPOSITORY_TAG="${YOUR_DOCKERHUB_USERNAME}/${SERVICE_NAME}:${BUILD_ID}"
	}
    
    stages {
        stage('Build docker image') {
            steps {
                sh 'docker build --file frontend/Dockerfile -t ${REPOSITORY_TAG} frontend/'
            }
        }
        stage('Login to DockerHub') {
			steps {
				sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
			}
		}
        stage('Push docker image to registry') {
            steps {
                sh 'docker push ${REPOSITORY_TAG}'
            }
        }
        stage('Deploy to Cluster') {
          steps {
                sh 'envsubst < ${WORKSPACE}/frontend/deploy.yaml | kubectl apply -f -'
            }
        }
    }
}
