pipeline {
    agent any
    
    environment {
		DOCKERHUB_CREDENTIALS=credentials('credential-docker')
		YOUR_DOCKERHUB_USERNAME="ulviibadov"
        SERVICE_NAME = "backend-app-service"
        REPOSITORY_TAG="${YOUR_DOCKERHUB_USERNAME}/${SERVICE_NAME}:${BUILD_ID}"
        SONAR_LOGIN='d0d400d55ab6687703de6707174a948aa6575b65'
	}

    stages {
        stage('Build & tests ') {
            steps {
                dir('backend'){
                    echo 'Building..'
                    sh "./gradlew build --no-daemon"
                    sh "./gradlew test"
                }

            }
        }

        stage('Sonarqube') {
            steps {
                dir('backend'){
                    sh './gradlew --info jacocoTestReport'
                    sh './gradlew --info sonarqube -Dsonar.host.url=http://sonarqube-service:9000 -Dsonar.projectKey=$SERVICE_NAME -Dsonar.projectName=$SERVICE_NAME -Dsonar.login=$SONAR_LOGIN'
                  }

            }
        }
        stage('Build docker image') {
            steps {
                sh 'docker build --file backend/Dockerfile -t ${REPOSITORY_TAG} backend/'
            }
        }
        stage('Login to DockerHub') {
			steps {
				sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
			}
		}
        stage('Push docker image to registry') {
            steps {
                sh 'docker push ${REPOSITORY_TAG}'
            }
        }
         stage('Deploy to Cluster') {
          steps {
                sh 'envsubst < ${WORKSPACE}/backend/deploy.yaml | kubectl apply -f -'
            }
        }
    }
}